### ISSUE TITLE
File Reference Broken

### ISSUE THREAD

**Issue by sangeethnandakumar** [ilovepdf/ilovepdf-php#1]
require_once dirname(__FILE__) . '/src/Exception.php';
require_once dirname(__FILE__) . '/src/Exceptions/Exception.php';

These files mentioned in init.php found to be missing as reported by my server.

**Comment by marcogrossisas** [comment]
Thanks a lot for reporting, we will look into it!

**Comment by maztch** [comment]
Updated init.php file on [261f719](https://github.com/ilovepdf/ilovepdf-php/commit/261f71972944b783554a4e421749f1f0416e8e69)
