### ISSUE TITLE
Development issue

### ISSUE THREAD

**Issue by Phpkite** [ilovepdf/ilovepdf-php#11]
Fatal error: Uncaught exception 'Ilovepdf\Exceptions\AuthException' with message 'Unauthorized' in D:\xampp2\htdocs\pdf\vendor\ilovepdf\ilovepdf-php\src\Ilovepdf.php:182 Stack trace: #0 D:\xampp2\htdocs\pdf\vendor\ilovepdf\ilovepdf-php\src\Task.php(72): Ilovepdf\Ilovepdf->sendRequest('get', 'start/compress', 'v=php.1.1.6') #1 D:\xampp2\htdocs\pdf\vendor\ilovepdf\ilovepdf-php\src\Task.php(65): Ilovepdf\Task->start() #2 D:\xampp2\htdocs\pdf\vendor\ilovepdf\ilovepdf-php\src\CompressTask.php(26): Ilovepdf\Task->__construct('project_public_...', 'secret_key_e679...', true) #3 D:\xampp2\htdocs\pdf\vendor\ilovepdf\ilovepdf-php\samples\compress_basic.php(12): Ilovepdf\CompressTask->__construct('project_public_...', 'secret_key_e679...') #4 {main} thrown in D:\xampp2\htdocs\pdf\vendor\ilovepdf\ilovepdf-php\src\Ilovepdf.php on line 182

**Comment by marcogrossisas** [comment]
Hello @Phpkite the problem may be the time that is set into your php, the time must be set correctly in your timezone. Is correct the time is set? You are receiving an error: \UnauthorizedHttpException: Expired token.
