### ISSUE TITLE
Image to PDF is not working correctly

### ISSUE THREAD

**Issue by divsbhalala** [ilovepdf/ilovepdf-php#12]
I have tired one image that I have it's not converting properly all the color of that PDF is inverse.
Here is the video that I have create for your demo
https://developer.ilovepdf.com/docs/guides/office-to-pdf-api
and here is an image that I am using 
[66-Caheranne-2_3065441_22-11-2017_toPDF.pdf](https://github.com/ilovepdf/ilovepdf-php/files/1495291/66-Caheranne-2_3065441_22-11-2017_toPDF.pdf)

**Comment by marcogrossisas** [comment]
Hello @divsbhalala ,

I'm sorry but I can't see the video (is a link to the Office to PDF API) and the image is a PDF, can you send the original image you want to convert to PDF so we can test it? 
Thanks!

**Comment by divsbhalala** [comment]
![66 caheranne](https://user-images.githubusercontent.com/12185309/33128764-9527cd40-cfb3-11e7-9e80-eb0011117c8c.jpg)
https://www.screenmailer.com/v/sZb3Dqca1PwDr38

@marcogrossisas sorry,
this is Image and URL that I am trying

**Comment by marcogrossisas** [comment]
@divsbhalala The problem has been fixed, please retry and inform us if now it works as expected.

**Comment by divsbhalala** [comment]
@marcogrossisas thank's it's working now
