### ISSUE TITLE
Call to undefined method Ilovepdf\WatermarkTask::setOpacity()

### ISSUE THREAD

**Issue by divsbhalala** [ilovepdf/ilovepdf-php#13]
When setting opacity into watermark task getting error function undefined
http://prntscr.com/heovse

**Comment by maztch** [comment]
Hello divsbhalala, the method is `setTransparency`

**Comment by divsbhalala** [comment]
@marcogrossisas I also tried that method but setting transparency is not working

**Comment by maztch** [comment]
try it now: setTransparency(0) is full transparent, setTransparency(100) is full opaque

**Comment by divsbhalala** [comment]
@maztch it's working now
