### ISSUE TITLE
Set opacity is not working

### ISSUE THREAD

**Issue by divsbhalala** [ilovepdf/ilovepdf-php#15]
Set opacity is not working while adding image into watermark task 
Please test here https://www.tweak.com/add-watermark-pdf/

**Comment by divsbhalala** [comment]
Here is my code 

    public function addWatermarkToPdf($files, $watermark_type='text', $watermark_text='', $watermark_image='', $fontSize=18, $fontColor='#000',
    $fontFamily='courier', $range='all', $horizontalPosition='left', $verticalPosition='bottom', $opacity=50, $page_layer_pos='bottom', $watermark_rotation=35, $rotation=[], $name, $pkjFileName){

        $watermark = new WatermarkTask( $this->publicKey, $this->secretKey );
        foreach ($files as $key => $file) {
            $fileA = $watermark->addFile($file);
            $fileA->setRotation($rotation[$key] ? $rotation[$key] : 0);
        }
        // $fileA = $watermark->addFile($pdfFilePath);

        if($watermark_type=='text'){
            $watermark->setText($watermark_text);
            $watermark->setFontFamily($fontFamily);
            $watermark->setFontSize($fontSize);
            $watermark->setFontColor($fontColor);
        }
        else if(!empty($watermark_image)){
            $watermark->setMode('image');
            //$watermark->setImage($img);
            $image = $watermark->addFile($watermark_image);
            $watermark->setImage($image->server_filename);
        }

        // $watermark->setMosaic(true);
        $watermark->setPages($range);
        $watermark->setHorizontalPosition($horizontalPosition);
        $watermark->setVerticalPosition($verticalPosition);
        $watermark->setTransparency($opacity);
        // $watermark->setOpacity($opacity);
        $watermark->setLayer($page_layer_pos);
        $watermark->setRotation($watermark_rotation);

        $watermark->setOutputFilename($name);
        $watermark->setPackagedFilename($pkjFileName);
        // print_r($watermark);
        $watermark->execute();
        //print_r($watermark);
        return $watermark;
    }

**Comment by maztch** [comment]
Sorry, but I checked it right now and it's working...in our api and in your implementation.

What image are you using? Can you add it here?

**Comment by divsbhalala** [comment]
![66 caheranne](https://user-images.githubusercontent.com/12185309/33601646-da416caa-d9d2-11e7-8b51-5ea9eb8f1991.jpg)
I am using this image

**Comment by divsbhalala** [comment]
[Product List Instruction.pdf](https://github.com/ilovepdf/ilovepdf-php/files/1530693/Product.List.Instruction.pdf)
And Using this PDF

**Comment by divsbhalala** [comment]
[Product-List-Instruction_9475640_05-12-2017_watermark_image.pdf](https://github.com/ilovepdf/ilovepdf-php/files/1530697/Product-List-Instruction_9475640_05-12-2017_watermark_image.pdf)
Ia m getting this PDF as output

**Comment by maztch** [comment]
Ok, it's a cmyk image. Your code is correct. We are solving it on our api servers.

**Comment by divsbhalala** [comment]
Ok thanks

**Comment by maztch** [comment]
Done, try it now.

**Comment by divsbhalala** [comment]
ok let me check
