### ISSUE TITLE
issue in generating excel file from pdf file

### ISSUE THREAD

**Issue by manojnagar21** [ilovepdf/ilovepdf-php#24]
i am able to get proper excel from your website - https://www.ilovepdf.com/pdf_to_excel.

but not able to produce the same results in excel when using developers console api - https://github.com/ilovepdf/ilovepdf-php/blob/master/samples/extract_advanced.php.

can you give me the api from php samples folder that can generate excel with tables from pdf file.

**Comment by maztch** [comment]
pdf to office tools are not currently available on the api, sorry
