### ISSUE TITLE
[Solved] Call to undefined function execute()

### ISSUE THREAD

**Issue by danuri** [ilovepdf/ilovepdf-php#25]
I have following code from example
`use Ilovepdf\Ilovepdf;`

`$ilovepdf = new Ilovepdf('xxx','xxx');
 $myTaskConvertOffice = $ilovepdf->newTask('officepdf');
 $file1 = $myTaskConvertOffice->addFile('uploads/'.$filename);
 $myTaskConvertOffice>execute();
 $myTaskConvertOffice->download('uploads/');`

And this error response:
`Call to undefined function execute()`

Any rules Iam miss?

**Comment by danuri** [comment]
Sorry, there typo in my code
`$myTaskConvertOffice>execute();`
to
`$myTaskConvertOffice->execute();`

**Comment by qant** [comment]
Because this typo in docs on this page https://developer.ilovepdf.com/docs/guides/office-to-pdf-api, copy past protection =)))

**Comment by maztch** [comment]
New developers website is coming!
