### ISSUE TITLE
Fatal error: Uncaught InvalidArgumentException: File /uploadpdf/1495.pdf does not exists in C:\xampp\htdocs\Spot\Spot\vendor\ilovepdf-php\src\Task.php:191

### ISSUE THREAD

**Issue by valjuniel123** [ilovepdf/ilovepdf-php#28]
Fatal error: Uncaught InvalidArgumentException: File /uploadpdf/1495.pdf does not exists in C:\xampp\htdocs\Spot\Spot\vendor\ilovepdf-php\src\Task.php:191 Stack trace: #0 C:\xampp\htdocs\Spot\Spot\vendor\ilovepdf-php\src\Task.php(162): Ilovepdf\Task->uploadFile('g27d4mrsg3ztmnz...', '/uploadpdf/1495...') #1 C:\xampp\htdocs\Spot\Spot\api_ilovepdf.php(18): Ilovepdf\Task->addFile('/uploadpdf/1495...') #2 {main} thrown in C:\xampp\htdocs\Spot\Spot\vendor\ilovepdf-php\src\Task.php on line 191

**Comment by maztch** [comment]
Ensure the file exists before add it.
if(!file_exists($file)) { throw new \Exception('file not exists); }
