### ISSUE TITLE
Fatal error: Uncaught exception 'Exception' with message 'SSL certificate problem: unable to get local issuer certificate' in C:\ilovepdf-php\src\Request.php on line 396

### ISSUE THREAD

**Issue by hnk15** [ilovepdf/ilovepdf-php#3]
Fatal error: Uncaught exception 'Exception' with message 'SSL certificate problem: unable to get local issuer certificate' in C:\ilovepdf-php\src\Request.php on line 396

Exception: SSL certificate problem: unable to get local issuer certificate in C:\ilovepdf-php\src\Request.php on line 396

Why we are getting this error?

**Comment by marcogrossisas** [comment]
@hnk15 This error message tells that you need to install a local certificate when using curl to call a https url. Take a look on how to install it: https://stackoverflow.com/questions/28858351/php-ssl-certificate-error-unable-to-get-local-issuer-certificate

Anyway, we just added a new function $ilovepdf->verifySsl(true). If you set it to false the curl connection won't verify anymore the remote certificate and you won't get an error. But we **strongly recommend** always to set it to true always for security reasons. Please update to the 1.1.3 version of the library.

**Comment by hnk15** [comment]
Ok I've solved this issue for me.  Hopefully others experiencing the same problem might benefit from me sharing this.

It's a php config issue.

It's easy to fix (php 5.3.7 or higher) - [Download](https://www.google.com/url?q=http%3A%2F%2Fcurl.haxx.se%2Fca%2Fcacert.pem&sa=D&sntz=1&usg=AFQjCNE0xlPAnyfNa_tlCkt4guaHpEz3kw) a list file with an up-to-date certificate authorities, and add this setting to your php.ini
curl.cainfo=<path-to>cacert.pem

Please remember the required to be an absolute path.
Restart your web server, and it'll work !

Hope that helps thanks!

**Comment by hnk15** [comment]
@marcogrossisas, Thanks for your reply!
