### ISSUE TITLE
PHP 8: Required parameter $response follows optional parameter $code

### ISSUE THREAD

**Issue by eswachsman** [ilovepdf/ilovepdf-php#31]
When I upgraded to PHP 8, I am getting this error: Required parameter $response follows optional parameter $code

Is PHP 8 not supported yet?

**Comment by maztch** [comment]
It should work, i'll test again

**Comment by cristianoc72** [comment]
It works on Linux and Windows but not on MacOs. Try to understand why...

**Comment by eswachsman** [comment]
Was this issue closed because it was fixed? Because I am encountering this issue again.
