### ISSUE TITLE
Rearrange pages 

### ISSUE THREAD

**Issue by renatovaler** [ilovepdf/ilovepdf-php#41]
How to rearrange pages of multiple pdfs simultaneously?

Like this: https://www.ilovepdf.com/organize-pdf

**Comment by maztch** [comment]
It's just a split with a merge after. ex: if you have 5 pages you can split: "3-5,1-2" and set the merge after to true

**Comment by buzzclue** [comment]
It would be great if you add an example of organize. There's no reference in documentation either how organize PDF tool is setup or can be done using API only.
