### ISSUE TITLE
Webhook is never triggered

### ISSUE THREAD

**Issue by Radon8472** [ilovepdf/ilovepdf-php#43]
I tried to run a task, that should trigger a webhook when finished (Like [example webhook_send]).

That is my code:
```php
require_once('vendor/autoload.php');

use Ilovepdf\OfficepdfTask;

// Load my keys into $keys
$myTask = new OfficepdfTask($keys[0],$keys[1]);
$file1 = $myTask->addFile('my-test.ppt');
$myTask->setOutputFilename('outfile-office.pdf');

$myTask->setWebhook('http://my-url.de:20000/pdf-download-hook');

// We don't download here because with the webhook we ordered the files must be processed in background.
// Notification will be sent once it's ready

//   $myTask->execute(); // see info add "Own research"
```

# Expected behavior:
- WebHook-url should be triggered, when task is done.

# Actual behavior:
- WebHook is never triggered

# Own reseach:
- I noticed, that the method `setWebhook()` does not trigger any server-requests, so I tried to add
  ```php
  $myTask->execute();
  ``` 
   because [documentation] says `webhook` should be send with `POST https://{server}/v1/process`. But the webhook still is not triggered.
- the same script works fine, when I remove "setWebhook" and add a `$myTask->download()` at the end -> so I`m quite there are no issues with api key, internet connection or anything similar.
- I sure my webhook url is reachable from public internet too

**EDIT:** When I add the same webhook as webhook into my global api config, it is called successfull, but dynamical adding webhooks via [Task->setWebhook()] seems to have no effect.

[example webhook_send]: https://github.com/ilovepdf/ilovepdf-php/blob/b79c79a9ed3fd65ac611f3cb53917be68af10c34/samples/webhook_send.php
[documentation]: https://developer.ilovepdf.com/docs/api-reference#process
[Task->setWebhook()]: https://github.com/ilovepdf/ilovepdf-php/blob/b79c79a9ed3fd65ac611f3cb53917be68af10c34/src/Task.php#L784C28-L784C31

**Comment by maztch** [comment]
`setWebook` method will be changed to `setProcessInBackground`. This will send the process task to be run on background and no wait for response, params will be `true` or `false`
