### ISSUE TITLE
cURL error 7

### ISSUE THREAD

**Issue by Mostafa-shenawy** [ilovepdf/ilovepdf-php#45]
This is my code to convert html to PDF, but I get cURL error 7

```
$ilovepdf = new Ilovepdf('{public_key}','{secret_key}');

$myTaskHtmlpdf = $ilovepdf->newTask('htmlpdf');

$file = $myTaskHtmlpdf->addUrl($post_url);

$myTaskHtmlpdf->execute();

$myTaskHtmlpdf->download();
```

This is the error details

PHP Fatal error:  Uncaught GuzzleHttp\Exception\ConnectException: cURL error 7:  (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://api32.ilovepdf.com/v1/upload in /vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:210

**Comment by maztch** [comment]
this looks like a network issue...please reopen if you find it persists
