### ISSUE TITLE
Guzzle response missusage

### ISSUE THREAD

**Issue by flohw** [ilovepdf/ilovepdf-php#48]
Hello,

I use your library inside a Symfony project and set a webhook to be able to mark the contract signed and assign signed files to my contract in my DB.
I wanted to use the `SignatureManagement::getSignatureStatus(string $signatureId)` method but I get the following warning message : `Undefined property: GuzzleHttp\\Psr7\\Response::$body` (in [SignatureManagement.php:48](https://github.com/ilovepdf/ilovepdf-php/blob/23eceed19a94cab2cba224d38846787491e2c7f2/src/SignatureManagement.php#L48))

The installed Guzzle version is 7.8.1. The right way to get the response content with guzzle is `$response->getBody()->getContents()` which in your case should be `json_enocode`d.
The same apply to the other lines where `->body` is used like in `getSignaturesList():31`

I can provide a patch for this single error but I am not sure about the compatibility.

Let me know if I need to open a PR for this.

Thank you

[EDIT]: After some other inspection it appears that the whole file is not using response from guzzle properly. The `headers` property used at line 29 should be a `getHeaders()` call and maybe the usage should be updated.
Let me know if you need help for this. I am not available for the next week but will be happy to help on the different updates to fix these issues.

As a workaround for now I instantiate a `SignatureManagement` with my private et secret key. Then I use the Symfony HttpClient to call the requestreview endpoint and use the `SignatureManagement::getJWT()` method to provide the `Authorization` header.

**Comment by maztch** [comment]
Thanks for reporting the issue. I'll try to check it and find a way to make it compatible.

**Comment by maztch** [comment]
This should be solved on #49

**Comment by flohw** [comment]
I updated the library. It works as expected. Thanks.
