### ISSUE TITLE
Typing inconsistency

### ISSUE THREAD

**Issue by flohw** [ilovepdf/ilovepdf-php#57]
Hi,

I use PHPStan within my project and use your library.
PHPStan reports some errors on `ElementAbstract` when we use it's derivations such as `ElementSignature`.

Mainly when chaining methods.

See here: https://phpstan.org/r/42328237-5731-43f3-bff4-ca2408a50694

When removing the `@return` tag or replacing by `@return $this`, there will be no error.

Would you mind if I provide a PR with this kind of improvements?

Thanks

**Comment by Malove98** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by maztch** [comment]
Should be solved in newer versions. Please feel free to do PR if needed!
